PenteractStudios/Tesseract

Project/Source/Modules/ModuleTime.cpp

In ModuleFiles the function 'EraseFile' was changed to 'Erase'. Not updated in the source file ModuleTime.cpp

Mismatch function name

---

Project/Source/Components/ComponentBoundingBox.cpp
Project/Source/Components/ComponentTransform.cpp
Project/Source/Modules/ModuleScene.cpp
Project/Source/Resources/GameObject.cpp
Project/Source/Resources/GameObject.h

Fixed merge errors with Components and Duplicate Components

Fix Merge errors with Duplicate_Components

---

Game/Assets/Shaders/SkyboxShader.glsl.meta
Game/Assets/Skybox/cubemap.sky.meta
Project/Source/FileSystem/MaterialImporter.cpp
Project/Source/FileSystem/ModelImporter.cpp
Project/Source/FileSystem/SceneImporter.cpp
Project/Source/FileSystem/ShaderImporter.cpp
Project/Source/FileSystem/SkyboxImporter.cpp
Project/Source/FileSystem/TextureImporter.cpp
Project/Source/Modules/ModuleResources.cpp
Project/Source/Modules/ModuleResources.h
Project/Source/Resources/ResourceType.h

Será necesario cambiar ligeramente los importers con este fix implementado. Los importers de develop están cambiados como ejemplo de lo que hay que hacer.

Fix resource import being stuck in a loop

---

Project/Source/FileSystem/SceneImporter.cpp
Project/Source/FileSystem/SceneImporter.h
Project/Source/Modules/ModuleTime.cpp
Project/Source/Resources/ResourceScene.cpp

Hay un bug de Git con el cambio en SceneImporter. Simplemente he eliminado el comentario que había al final.

Fix play/stop buttons not creating a temporary scene

---

Project/Source/Components/ComponentScript.cpp
Project/Source/Components/ComponentScript.h
Project/Source/Components/UI/ComponentButton.cpp
Project/Source/Components/UI/ComponentCanvas.cpp
Project/Source/Components/UI/ComponentCanvas.h
Project/Source/Components/UI/ComponentCanvasRenderer.cpp
Project/Source/Components/UI/ComponentCanvasRenderer.h
Project/Source/Modules/ModuleUserInterface.cpp
Project/Source/Scene.h
Project/Source/Script.h

OnButtonClick function of Script is overridable

ComponentButton's OnClicked function calls owner's scripts OnButtonClick methods

---

Project/Source/GameplaySystems.h
Project/Source/Panels/PanelInspector.cpp

[hotfix] Be able to change the name of a game object
[hotfix] Include float2 to GameplaySystem.h

[Hotfix] PanelInspector / GameplaySystem

---

Project/Source/GameplaySystems.cpp
Project/Source/GameplaySystems.h
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelConfiguration.cpp
Project/Source/Panels/PanelScene.cpp

[Hotfix] Move Draw options to the correct Panel
[feature] bool to activate DebugMode in ModuleRender (FYI: @FrancPS @Mefiso)

Move Draw options to the correct Panel

---

Project/Source/FileSystem/TextureImporter.cpp
Project/Source/Modules/ModuleUserInterface.cpp
Project/Source/Resources/ResourceTexture.cpp

Lowy fixed Texture Flipping
Buttons are now not enabled until play mode.

Texture flipping fixed

---

Project/Tesseract.vcxproj

This will make compilation multiple times faster.

Add /MP to compilation options (multi-processor compilation)

---

Project/Source/Modules/ModuleProject.cpp

Before doing the component script's update, we were not checking if the component was active

Fixed bug where component script ignored active condition

---

Project/Source/Components/UI/ComponentImage.cpp

Fixed a bug where ComponentImage would render excessively scaled in debug mode.

Fixed 3D view of the image

---

Project/Source/Modules/ModuleProject.cpp
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleResources.cpp
Project/Source/Modules/ModuleScene.cpp

Game View wasn't getting rendered correctly

Fixed bug where Game build wasn't working correctly

---

Project/Source/Components/UI/ComponentTransform2D.cpp
Project/Source/Panels/PanelHierarchy.cpp
Project/Source/Panels/PanelInspector.cpp

ComponentCanvas will now create Transform2D

---

Game/Assets/Scenes/ChangingCharacter.scene
Game/Assets/Scenes/CreditsScene.scene
Game/Assets/Scenes/GameControllerWinLose.scene
Game/Assets/Scenes/HowToPlay.scene
Game/Assets/Scenes/Level1.scene
Game/Assets/Scenes/LoseScene.scene
Game/Assets/Scenes/Slider.scene
Game/Assets/Scenes/Slider2.scene
Game/Assets/Scenes/StartScene.scene
Game/Assets/Scenes/VS1.scene
Game/Assets/Scenes/WinScene.scene
Project/Source/Components/Component.cpp
Project/Source/Components/Component.h
Project/Source/Components/ComponentAudioListener.cpp
Project/Source/Components/ComponentAudioListener.h
Project/Source/Components/ComponentAudioSource.cpp
Project/Source/Components/ComponentBoundingBox.cpp
Project/Source/Components/ComponentCamera.cpp
Project/Source/Components/ComponentLight.cpp
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Components/ComponentScript.cpp
Project/Source/Components/ComponentSkyBox.cpp
Project/Source/GameObject.cpp
Project/Source/GameObject.h
Project/Source/Modules/ModuleProject.cpp
Project/Source/Modules/ModuleUserInterface.cpp
Project/Source/Panels/PanelHierarchy.cpp
Project/Source/Panels/PanelInspector.cpp

There are changes in the GameObject / Component IsActive function and all calls of IsActiveInHierarchy have been replaced by IsActive.

GameObject and Component Enable / Disable bug fix

---

Game/Assets/Scripts/VolumeControl.cpp
Game/Assets/Scripts/VolumeControl.h
Project/Source/Components/ComponentAudioListener.cpp
Project/Source/Components/ComponentAudioListener.h

Simple script to modify game volume

Script to control game volume

---

Project/Source/MaskType.cpp
Project/Source/MaskType.h

Established MaskType for player collisions

Established MaskType for player

---

Project/Source/Components/ComponentCamera.cpp

Fast UX enhancement for new camera objects

Modified default far plane for Component Cameras

---

Project/Source/Components/UI/ComponentImage.cpp
Project/Source/Components/UI/ComponentImage.h
Project/Source/Components/UI/ComponentTransform2D.h

Exposed some methods so that Penteract can access them (Gameplay required methods)

Exposed some methods so that Penteract can access them

---

Project/Source/Components/ComponentAgent.cpp
Project/Source/Components/ComponentAgent.h

This parameter prevents the agent from decelerating when getting close to a wall

ComponentAgent Added AvoidingObstacle parameter

---

Project/Source/Panels/PanelProject.cpp

Folders are collapsed by default and there are individual scrollbars.

Improve PanelProject UX

---

Project/Source/Components/ComponentAgent.cpp
Project/Source/Components/ComponentAgent.h
Project/Source/Components/UI/ComponentImage.cpp
Project/Source/Components/UI/ComponentImage.h

Some methods required by penteract are now accessible

Added some methods that Gameplay requires

---

Project/Source/Modules/ModuleRender.cpp

Before changes
https://user-images.githubusercontent.com/24542154/120231247-4de62500-c251-11eb-96a0-3493b6f26053.mp4
After changes
https://user-images.githubusercontent.com/24542154/120231258-52aad900-c251-11eb-81fb-1e79c73fdcc6.mp4

Fixed shadows vs frustum culling

---

Project/Source/Components/UI/ComponentButton.cpp
Project/Source/Components/UI/ComponentEventSystem.cpp
Project/Source/Components/UI/ComponentSelectable.cpp
Project/Source/Components/UI/ComponentSlider.cpp
Project/Source/Components/UI/ComponentToggle.cpp
Project/Source/Modules/ModuleUserInterface.cpp

Navigation was working on a "2nd" plane, this shouldn't happen
CurrentEventSystem had a nullref exception

Navigation bugs fixed

---

Project/Source/Resources/ResourceMaterial.cpp

[hotfix] Add NormalStrength Serialization in ResourceMaterial

Add NormalStrength Serialization

---

Project/Source/Components/ComponentAudioListener.cpp
Project/Source/Components/ComponentAudioListener.h
Project/Source/Modules/ModuleEditor.cpp
Project/Source/Modules/ModuleEditor.h
Project/Source/Panels/PanelAudioMixer.cpp
Project/Source/Panels/PanelAudioMixer.h
Project/Tesseract.vcxproj
Project/Tesseract.vcxproj.filters

[feature] Implement Audio Mixer

Add audio mixer

---

Project/Source/Components/UI/ComponentProgressBar.cpp
Project/Source/Components/UI/ComponentProgressBar.h
Project/Source/Components/UI/ComponentSlider.h

I've been told to commit these changes directly under master so nothing else gets dragged into Master

Exposed members of some UI Components

---

Project/Source/Components/ComponentBillboard.cpp
Project/Source/Components/ComponentParticleSystem.cpp
Project/Source/Components/ComponentParticleSystem.h

[hotfix] Rotation in Billboard
[hotfix] Rotation in ParticleSystem
[feature] WIP: Attach to Emitter (only position)

Fix Particle System

---

Game/Assets/Scenes/Zombunny.scene
Game/Assets/Shaders/depthPrePass.shader
Game/Assets/Shaders/drawDepthMap.shader
Game/Assets/Shaders/drawSSAO.shader
Game/Assets/Shaders/fragmentStandard.shader
Game/Assets/Shaders/gaussianBlur.shader
Game/Assets/Shaders/ssao.shader
Game/Assets/Shaders/vertexScreen.shader
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Components/ComponentMeshRenderer.h
Project/Source/Components/ComponentSkyBox.cpp
Project/Source/Modules/ModulePrograms.cpp
Project/Source/Modules/ModulePrograms.h
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelConfiguration.cpp
Project/Source/Panels/PanelScene.cpp
Project/Source/Resources/ResourceTexture.cpp
Project/Source/Utils/Random.cpp
Project/Source/Utils/Random.h
Project/Tesseract.vcxproj
Project/Tesseract.vcxproj.filters

This PR includes:
- Depth Prepass
- SSAO
- Gaussian Blur
- Render refactor to facilitate new additions to the pipeline

Implement SSAO

---

Project/Source/Components/UI/ComponentEventSystem.h
Project/Source/GameplaySystems.cpp
Project/Source/GameplaySystems.h

- Created namespace in GameplaySystems for UserInterface
- Exposed function to be used in Gameplay

Expose methods for UI audio

---

Project/Source/Resources/ResourceClip.cpp
Project/Source/Resources/ResourceClip.h
Project/Source/Scripting/Script.h
Project/Source/StateMachineManager.cpp

In case of adding animation event add this line to .h
`void OnAnimationEvent(StateMachineEnum stateMachineEnum, const char* eventName) override;`
and to .cpp ej:
```
void AIMeleeGrunt::OnAnimationEvent(StateMachineEnum stateMachineEnum, const char* eventName)
{
if (stateMachineEnum == StateMachineEnum::PRINCIPAL)
{
if(std::strcmp(eventName, "Run") != 0){
// action
}
}
else if (stateMachineEnum == StateMachineEnum::SECONDARY)
{
if (std::strcmp(eventName, "Atack") != 0){
// action
}
}
}
```

Cu m19w3j key franes event animation

---

Game/Assets/Shaders/ImageUI.shader
Game/Assets/Shaders/colorCorrection.shader
Game/Assets/Shaders/fragmentPhong.shader
Game/Assets/Shaders/fragmentStandard.shader
Game/Assets/Shaders/skybox.shader
Game/Assets/Shaders/textUI.shader
Project/Source/Modules/ModulePrograms.cpp
Project/Source/Modules/ModulePrograms.h
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h

This PR fixes a few visual bugs we had with gamma correction and adds ACES tonemapping and gamma correction as post-processing effects.
Billboard and Trail shaders haven't been modified to avoid collisions, but they have to be changed too.

Implement ACES tonemapping

---

Project/Source/Modules/ModuleRender.cpp
Project/Source/Navigation/NavMesh.cpp

This makes the navmesh gizmo easier to work with,

Fix navmesh gizmo

---

Game/Assets/Shaders/fragmentUnlit.shader
Game/Assets/Shaders/vertexUnlit.shader
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Modules/ModulePrograms.cpp
Project/Source/Modules/ModulePrograms.h
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h
Project/Source/Resources/ResourceMaterial.cpp
Project/Source/Resources/ResourceMaterial.h

Added unlit shader that supports:
- Diffuse texture
- Diffuse color
- Emissive texture

Feature/cu kxdgzk Unlit shader

---

Project/Source/Components/ComponentAudioListener.cpp
Project/Source/Components/ComponentAudioListener.h
Project/Source/Components/ComponentAudioSource.h
Project/Source/FileSystem/AudioImporter.cpp
Project/Source/Resources/ResourceAudioClip.cpp

[hotfix] Disable converter for this alpha since is producing some problems

Disable Ogg converter

---

Game/Assets/Shaders/fragmentStandard.shader
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelConfiguration.cpp
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h

A new parameter for SSAO was added to make it easier to work with the current lighting conditions.

Add direct light SSAO

---

Project/Source/Resources/ResourceClip.cpp

Fix ResourceClip issue with Imgui labels

Fix ResourceClip issue with Imgui labels

---

Project/Source/Panels/PanelInspector.cpp
Project/Source/Panels/PanelInspector.h

[Plus] Added a menu for particles, trail and billboards

Removed double Add audio component options.

---

Project/Source/Modules/ModulePhysics.cpp
Project/Source/Modules/ModulePhysics.h

Just fixing this bug that we noticed the day before the alpha release

fixed skill layer interaction

---

Project/Source/Components/ComponentAudioSource.cpp
Project/Source/Components/ComponentAudioSource.h
Project/Source/Components/ComponentParticleSystem.cpp
Project/Source/Components/ComponentParticleSystem.h
Project/Source/Utils/ImGuiUtils.h

[feature] Play On Awake in PS and ComponentAudioSource
- Getters and Setters ComponentAudioSource
- General fixes
Tested in Game

Play On Awake PS and Audio

---

.gitignore
Project/Source/Application.cpp
Project/Source/Application.h
Project/Source/Globals.h
Project/Source/Modules/ModuleConfiguration.cpp
Project/Source/Modules/ModuleConfiguration.h
Project/Source/Modules/ModuleRender.h
Project/Source/Modules/ModuleScene.cpp
Project/Source/Modules/ModuleScene.h
Project/Source/Panels/PanelConfiguration.cpp
Project/Tesseract.vcxproj
Project/Tesseract.vcxproj.filters

This PR allows project-wide configuration to be saved in a file called config.json. This includes the starting scene and rendering information, among other data.

Implement configuration file

---

Game/Assets/Shaders/heightFog.shader
Project/Source/Components/ComponentCamera.cpp
Project/Source/Components/ComponentFog.cpp
Project/Source/Components/ComponentFog.h
Project/Source/Components/ComponentType.cpp
Project/Source/Components/ComponentType.h
Project/Source/Modules/ModulePrograms.cpp
Project/Source/Modules/ModulePrograms.h
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelInspector.cpp
Project/Source/Panels/PanelScene.cpp
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h
Project/Source/Scene.cpp
Project/Source/Scene.h
Project/Tesseract.vcxproj
Project/Tesseract.vcxproj.filters

This is an exponential height fog implementation using the positions texture as input.
Features:
- New fog component
- Density / falloff parameters
- Fog color (alpha is used as a max density limit)
- Multiple fog instances allowed
Currently not supported:
- Translucent object support (could be added later)
- Directional in-scattering (could be added later)

Exponential height fog

---

Project/Source/Components/UI/ComponentTransform2D.cpp
Project/Source/Components/UI/ComponentTransform2D.h

This is necesary for the implementation of the new UI features

Exposed rotation setter and getter, also changed it so it returns a Quad

---

Project/Source/GameplaySystems.cpp
Project/Source/GameplaySystems.h
Project/Source/Modules/ModuleInput.cpp
Project/Source/Modules/ModuleInput.h

Established basic vibration starting (with strength and duration parameters)
Made vibrations accessible through GameplaySystems

Basic controller vibration

---

Game/Assets/Shaders/trail.shader
Project/Source/Components/ComponentParticleSystem.cpp
Project/Source/Components/ComponentParticleSystem.h
Project/Source/Components/ComponentTrail.cpp
Project/Source/Components/ComponentTrail.h
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h
Project/Source/Utils/Trail.cpp
Project/Source/Utils/Trail.h

- [hotfix] Conflict between gradients in PS and Trails
- [clean] Keep order of code
- [feature] Add Randomness to Trail parameters
Note: We've detected some issues in the Trail Implementation. We will improve it in other PR. Trail stretch is on hold until this is solved. Basic operations from Trails are usable for this Alpha. Moreover, we need this PR approved ASAP to be able to work with VFX for the Alpha.

Trail hotfix

---

Project/Source/Components/ComponentAudioSource.cpp
Project/Source/Components/ComponentAudioSource.h

Add IsPaused() function to Gameplay

Add audio function to Gameplay

---

Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Components/ComponentMeshRenderer.h

These functions are requested by Gameplay to check whether if the Dissolve animation has finished or not. 
The idea, as I mentioned in other PRs is to have the possibility to control dissolve animation from Gameplay, but for now, this will suffice.

Dissolve Query functions

---

Game/Assets/Shaders/bloomCombine.shader
Game/Assets/Shaders/colorCorrection.shader
Project/Source/Modules/ModuleConfiguration.cpp
Project/Source/Modules/ModulePrograms.cpp
Project/Source/Modules/ModulePrograms.h
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelConfiguration.cpp
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h

This PR includes changes to the way bloom is calculated and a parameter to control the kernel size. Extra passes have been added to improve the quality.

Improve bloom

---

Project/Source/FileSystem/SceneImporter.cpp

Hotfix regarding scene loading cursor to prevent crashes

Hotfix to prevent crashes (Scene cursor loading)

---

Project/Source/Components/ComponentParticleSystem.cpp

Fix SubEmitters

---

Project/Libs/Bullet/include/BulletCollision/BroadphaseCollision/btDbvt.h
Project/Libs/Bullet/include/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h
Project/Libs/Bullet/include/LinearMath/btScalar.h
Project/Libs/Bullet/include/LinearMath/btSerializer.h
Project/Source/Animation/StateMachineEnum.h
Project/Source/Animation/StateMachineManager.cpp
Project/Source/Components/ComponentParticleSystem.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Scripting/Script.h

Removed all the 'unreferenced formal parameter ...'

Remove warnings from script class

---

Project/Source/Components/ComponentParticleSystem.cpp
Project/Source/Components/ComponentParticleSystem.h

New function for make easy the gameplay scripts

ParticlesPerSecondChild()

---

Project/Source/Components/ComponentBillboard.cpp
Project/Source/Components/ComponentBillboard.h

We have changed the behavior of the duration of the billboard adding cycles and loops to colorOverLifetime and AnimationSheet. This change is because we want to add some Billboards to the Boss fight and we need them this way

Modify Billboard lifetime

---

Game/Assets/Shaders/emptyShader.shader
Game/Assets/Shaders/fragmentDissolve.shader
Game/Assets/Shaders/fragmentStandard.shader
Game/Assets/Shaders/fragmentUnlit.shader
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h
Project/Source/Resources/ResourceMaterial.cpp
Project/Source/Resources/ResourceMaterial.h

This PR adds new options to the dissolve shader:
- Noise texture (If present will override simplex noise generation)
- Edge color separate from emissive color
- Edge intensity

Improve dissolve shader

---

Game/Assets/Shaders/fragmentPhong.shader
Game/Assets/Shaders/fragmentStandard.shader
Game/Assets/Shaders/lightCulling.shader
Project/Source/Components/ComponentMeshRenderer.cpp
Project/Source/Modules/ModuleRender.cpp
Project/Source/Modules/ModuleRender.h
Project/Source/Panels/PanelScene.cpp
Project/Source/Rendering/Programs.cpp
Project/Source/Rendering/Programs.h

This will fix lighting artifacts with transparent objects.

Fix transparent object light culling

---

Project/Source/Components/ComponentParticleSystem.cpp

This fixes particles not spawning with low FPS

Fix particle spawn

---

Project/Source/Components/UI/ComponentSelectable.h
Project/Source/Modules/ModuleUserInterface.cpp

Minor modifications in the way Keyboard/Gamepad manages ComponentSelectable clicked bool

Exposed ComponentSelectable->IsClicked() to Gameplay.
