PenteractStudios/Tesseract

- Project/Source/Modules/ModuleRender.cpp
- Project/Source/Panels/PanelHierarchy.cpp
- Project/Source/Utils/Quadtree.h
No estoy seguro si el `gameObject->flag = true;` deberia ir tambien dentro del `if(boundingBox)`.
En principio esto deberia arreglar el error, aunque me sorprende mucho que el error saltara ahí :S
O mejor dicho, por qué no saltaba aunque no se deleteen los objetos.
El engine petaba cuando eliminas el BabyPlayer, que es un objeto sin mesh->sin BB, y la camara no lo estaba enfocando (osea BabyP esta fuera del frustum). PERO solo peta cuando eliminar BabyPlayer es lo primero que haces, antes de mover incluso la camara. Si mueves un poco la camara y luego lo eliminas no petaba. No sé si puede haber algo mas profundo por ahi haciendo cosas raras.
> FIXED Crash on removing GameObjects

- Game/Assets/Scripts/GameController.cpp
- Game/Assets/Scripts/GameController.h
- Game/Assets/Scripts/StartController.cpp
Somebody changed the definition of SetRenderCamera camera. Now receives a ComponentCamera by parameter, but some scripts were sending a GameObject.
> Fixed scripts

- Project/Source/Components/UI/ComponentCanvas.cpp
- Project/Source/Components/UI/ComponentText.cpp
This makes other Components load with an initial incorrect size (p.eg: ComponentText)
> Fixed bug where ScreenFactor was 1 (absolute) when loading a scene

- Game/Assets/Shaders/ImageUI.shader
- Project/Source/Components/UI/ComponentButton.cpp
- Project/Source/Components/UI/ComponentImage.cpp
- Project/Source/Components/UI/ComponentImage.h
- Project/Source/Components/UI/ComponentSlider.cpp
- Project/Source/Components/UI/ComponentToggle.cpp
- Project/Source/Modules/ModuleUserInterface.cpp
- Project/Source/Modules/ModuleUserInterface.h
Tint Color has been removed from Shader and ComponentImage uses the main color of the ComponentSelectable in case it needs it (p.eg: when Selectable is hovered, selected or clicked).
As is:
ComponentImage has a color, and ComponentSelectable was used as a tint on the color.
To be:
If ComponentImage has a button, slider or toggle, will use their current state color as main color instead of tint.
> ComponentImage will use ComponentSelectable Main color as main color

- Project/Source/GameObject.cpp
Fixed! Right now the UIComponents are updated in the viewport at the same time changes the hierarchy between them.
PD: Sorry for the name of the branch, I believed that only happen this problem with UIText XD
> Hotfix: UI Components updated in the viewport at the same time that in the hierarchy 

- Game/Assets/Shaders/fragmentPhong.shader
- Game/Assets/Shaders/fragmentStandard.shader
- Project/Source/Resources/ResourceMaterial.cpp
- Project/Source/Utils/ImGuiUtils.h
- [Hotfix] Add Tiled UVs to new Maps
- *Reorganize ResourceMaterial UI
- Clean shaders code
*The idea of adding the texture miniature is to have feedback that something is attached, not to show a big texture. It should be shown in the Resource Texture UI. Now it's so difficult to understand how the materials work and could be a problem when we operate with them in the game development. I put again the format from before, that's simpler. 
VS
I keep the ID for now since I think is useful to check discrepancies with meta files (I would remove it). I will add the big texture with its information in the Resource Texture in another PR.
If you think any change is useless, please tell me and we can discuss it.
> Fix shaders / Modify ResourceMaterial

- Project/Source/Components/ComponentAgent.cpp
When the Player is standing IDLE, and Gameplay sets the position to itself, it will automatically go to (1*moveSpeed, 0, 0) due to the normalization of newPosition - agent.pos, which returns (1, 0, 0) when should be (0, 0, 0)
> ComponentAgent Fix

- Project/Source/Components/UI/ComponentSlider.cpp
- Project/Source/Components/UI/ComponentSlider.h
I update two methods in the `ComponentSlider.cpp/h` to use them in a script that it will work as a Game Manager in Penteract, between scenes.
Its use will be to control the volume during the game right now...in the future we can put variable that we need during all the game's life, like the points or something like that.
**NOTE: GameManager will be introduced in next delivery (Alpha 1), so there is no rush to accept this PR.**
> Feature: Update Component Slider to works methods in scripts

- Project/Source/Panels/PanelHierarchy.cpp
- Project/Source/Panels/PanelHierarchy.h
Implemented the duplicate GameObject feature when right-clicking one element in the hierarchy.
> Duplicate feature

- Game/Assets/Shaders/billboard.shader
- Game/Assets/Shaders/depthPrePass.shader
- Project/Source/Components/ComponentParticleSystem.cpp
- Project/Source/Components/ComponentParticleSystem.h
- Project/Source/Modules/ModuleRender.cpp
- Project/Source/Modules/ModuleRender.h
- Project/Source/Rendering/Programs.cpp
- Project/Source/Rendering/Programs.h
This PR adds a new option on particle effects: Soft particles. Soft particles allow particles to fade when they are near the level geometry so that hard edges aren't visible.
Added options:
- Soft (true / false)
- Soft range (Distance to the geometry before turning fully opaque)
> Soft particles

- Project/Source/FileSystem/TextureImporter.cpp
- Project/Source/Resources/ResourceTexture.cpp
Textures were being compressed on import, which is not the default behavior we want. This fixes multiple visual problems with the scene, including:
- Textures having improper colors
- Normal mapping artifacts
It would be a good idea to allow compression / decompression of individual textures, but this will be done separately.
> Fix texture compression

- Game/Assets/Materials/SpheresIBL/Sphere02.mat
- Game/Assets/Scenes/IBL.scene
- Game/Assets/Shaders/fragmentPhong.shader
- Game/Assets/Shaders/fragmentStandard.shader
- Project/Source/Components/ComponentLight.cpp
- Project/Source/Components/ComponentLight.h
- Project/Source/Components/ComponentMeshRenderer.cpp
- Project/Source/Components/ComponentSkyBox.cpp
- Project/Source/Components/ComponentSkyBox.h
- Project/Source/Rendering/Programs.cpp
- Project/Source/Rendering/Programs.h
Lights will now attenuate in a more physically accurate way. There is an added checkbox to use an exponential falloff if necessary.
- Point lights and Spotlights now use lumens as the intensity unit.
- Light attenuation is the same for all lights unless stated otherwise (using a custom falloff)
- Added a range for lights. This range doesn't affect the intensity of the light unless an exponential falloff is used.
- Skyboxes now have an added strength parameter to change the power of the ambient lighting.
GAMEPLAY: This will require reworking the scene lighting to use the new parameters.
> Improve light attenuation

- Game/Assets/Shaders/volumetricLight.shader
- Project/Source/Components/ComponentMeshRenderer.cpp
- Project/Source/Modules/ModulePrograms.cpp
- Project/Source/Modules/ModulePrograms.h
- Project/Source/Rendering/Programs.cpp
- Project/Source/Rendering/Programs.h
- Project/Source/Resources/ResourceMaterial.cpp
- Project/Source/Resources/ResourceMaterial.h
This PR includes a new material shader for volumetric lights (Halos, spotlight cones, godrays, holograms...)
Parameters:
- Volumetric Light Texture (Works like a diffuse map)
- Volumetric Light Color (multiplier)
- Intensity (Color multiplier)
- Attenuation Exponent (Attenuation based on direction to the camera)
- Soft / Softness range (Attenuation based on distance to other objects)
> Volumetric lighting

- Project/Source/GameplaySystems.cpp
- Project/Source/GameplaySystems.h
- Project/Source/Modules/ModuleNavigation.cpp
- Project/Source/Modules/ModuleNavigation.h
Added Raycast query function for wall detection of the NavMesh. This was requested by @GBMiro in order to detect the furthest position the enemies can be pushed by Fang's Push ability.
This function can be called from Gameplay with the new namespace Navigation just like this:
`Navigation::Raycast(float3 source, float3 target, bool hasHit, float3 hitPosition);` 
A quick test can be seen in the next GIF: 
- X Positive is right
- Source position is the bottom of the gif.
> NavMesh Raycast query function

- Project/Source/Components/ComponentScript.cpp
- Project/Source/Modules/ModuleEditor.h
- Project/Source/Scripting/Member.cpp
- Project/Source/Scripting/Member.h
Added a new Expose Member function to separate Script's variables.
This is the result:
Generated by the following code:
> Scripts Members Separator

- Game/Assets/Shaders/colorCorrection.shader
- Project/Source/GameplaySystems.cpp
- Project/Source/GameplaySystems.h
- Project/Source/Modules/ModuleConfiguration.cpp
- Project/Source/Modules/ModuleRender.cpp
- Project/Source/Modules/ModuleRender.h
- Project/Source/Panels/PanelConfiguration.cpp
- Project/Source/Rendering/Programs.cpp
- Project/Source/Rendering/Programs.h
Now Chromatic Aberration can be applied to the scene. Just like other postprocess/color correction settings, Chromatic Aberration can be set from Configuration tab.
**The default value to apply Chromatic Aberration Strength is 1. From 0 to 1 is an attenuated value, > 1 is an exaggerated value and < 0 may lead to unexpected results.**
It can also be accessed from Gameplay with the following methods from the namespace Screen:
> Chromatic aberration implementation

- Project/Source/FileSystem/ModelImporter.cpp
It was assumed that all the meshes in an fbx would have the same bones. This would cause an error because the Gameobjects would have "bones" even if they didn't, and that caused some rendering problems!
> Fixed model import problems

- Project/Source/FileSystem/TextureImporter.cpp
- Project/Source/FileSystem/TextureImporter.h
- Project/Source/Modules/ModuleResources.cpp
- Project/Source/Resources/ResourceTexture.cpp
- Project/Source/Resources/ResourceTexture.h
Textures can now be compressed to save VRAM and disk space.
> Implement texture compression

- Project/Source/Modules/ModuleResources.cpp
This fixes a crash that happened quite often when reloading materials.
> Fix import deadlock crash

- Project/Source/Components/UI/ComponentSlider.cpp
- Project/Source/Components/UI/ComponentSlider.h
This hotfix prevents a navigation error if you start handling a slider and then hide the navigation elements by unpausing.
> ComponentSlider must stop being handled on disable.
